---
- name: Ensure Grafana and Prometheus are accessible
  hosts: main
  gather_facts: true
  tasks:
    - name: Grafana
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}:3000
        follow_redirects: none
        status_code: [302]
    - name: Prometheus
      ansible.builtin.uri:
        url: http://{{ inventory_hostname }}:9090
        follow_redirects: none
        status_code: [302]
